# Generated by Django 5.2.8 on 2025-12-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='images/default.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
